export const VENDOR_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
} as const;

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const STORE_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
} as const;

export const GENERIC_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;

export const CUSTOMER_STATUS = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
} as const;

export const ADDRESS_TYPES = {
  HOME: 'HOME',
  WORK: 'WORK',
  OTHER: 'OTHER',
} as const;

export const DISCOUNT_TYPES = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED',
} as const;

export const COMMISSION_LEVELS = {
  GLOBAL: 'GLOBAL',
  LOCATION: 'LOCATION',
  VENDOR: 'VENDOR',
  STORE: 'STORE',
} as const;

export const INVENTORY_TRANSACTION_TYPES = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  RETURN: 'RETURN',
  DAMAGE: 'DAMAGE',
  ADJUSTMENT: 'ADJUSTMENT',
  RESERVATION: 'RESERVATION',
  RELEASE: 'RELEASE',
} as const;

export const NOTIFICATION_TYPES = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_PREPARING: 'ORDER_PREPARING',
  ORDER_READY: 'ORDER_READY',
  PARTNER_ASSIGNED: 'PARTNER_ASSIGNED',
  ORDER_PICKED_UP: 'ORDER_PICKED_UP',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  REFUND_COMPLETED: 'REFUND_COMPLETED',
  SETTLEMENT_COMPLETED: 'SETTLEMENT_COMPLETED',
} as const;

export const REVIEW_TARGET_TYPES = {
  VENDOR: 'VENDOR',
  STORE: 'STORE',
  PRODUCT: 'PRODUCT',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
} as const;

export const REVIEW_STATUS = {
  VISIBLE: 'VISIBLE',
  HIDDEN: 'HIDDEN',
} as const;

export const BANNER_PLACEMENTS = {
  GLOBAL: 'GLOBAL',
  LOCATION: 'LOCATION',
  FOOD: 'FOOD',
  INSTAMART: 'INSTAMART',
  VENDOR: 'VENDOR',
  STORE: 'STORE',
} as const;

export const DEVICE_TYPES = {
  ANDROID: 'ANDROID',
  IOS: 'IOS',
  WEB: 'WEB',
} as const;
