import { ADMIN_ROLES } from './roles';

export const PERMISSION_ACTIONS = {
  VIEW: 'VIEW',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  EXPORT: 'EXPORT',
} as const;

export const PERMISSIONS = {
  VENDOR_VIEW: 'VENDOR_VIEW',
  VENDOR_CREATE: 'VENDOR_CREATE',
  VENDOR_UPDATE: 'VENDOR_UPDATE',
  VENDOR_DELETE: 'VENDOR_DELETE',
  VENDOR_APPROVE: 'VENDOR_APPROVE',

  STORE_VIEW: 'STORE_VIEW',
  STORE_CREATE: 'STORE_CREATE',
  STORE_UPDATE: 'STORE_UPDATE',
  STORE_DELETE: 'STORE_DELETE',

  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_CANCEL: 'ORDER_CANCEL',

  DELIVERY_VIEW: 'DELIVERY_VIEW',
  DELIVERY_ASSIGN: 'DELIVERY_ASSIGN',
  DELIVERY_REASSIGN: 'DELIVERY_REASSIGN',

  DELIVERY_ZONE_VIEW: 'DELIVERY_ZONE_VIEW',
  DELIVERY_ZONE_MANAGE: 'DELIVERY_ZONE_MANAGE',

  // Issues raised against a specific delivery (customer complaint, vehicle
  // problem, ...) — distinct from DELIVERY_VIEW/ASSIGN/REASSIGN, which are
  // about the delivery's own in-flight status.
  DELIVERY_ISSUE_VIEW: 'DELIVERY_ISSUE_VIEW',
  DELIVERY_ISSUE_MANAGE: 'DELIVERY_ISSUE_MANAGE',

  // Delivery partner account management (CRUD/approval) — distinct from
  // DELIVERY_VIEW/ASSIGN/REASSIGN, which are about deliveries in flight.
  DELIVERY_PARTNER_VIEW: 'DELIVERY_PARTNER_VIEW',
  DELIVERY_PARTNER_MANAGE: 'DELIVERY_PARTNER_MANAGE',

  // Categories/subcategories are admin-managed taxonomy.
  FOOD_CATALOG_VIEW: 'FOOD_CATALOG_VIEW',
  FOOD_CATALOG_MANAGE: 'FOOD_CATALOG_MANAGE',
  // Products/variants/addons are vendor-owned; admins with this permission can
  // also manage them (scoped to their location), alongside the owning vendor.
  FOOD_PRODUCT_VIEW: 'FOOD_PRODUCT_VIEW',
  FOOD_PRODUCT_MANAGE: 'FOOD_PRODUCT_MANAGE',

  // Instamart categories/subcategories: admin-managed taxonomy (mirrors Food).
  INSTAMART_CATALOG_VIEW: 'INSTAMART_CATALOG_VIEW',
  INSTAMART_CATALOG_MANAGE: 'INSTAMART_CATALOG_MANAGE',
  // Instamart products/inventory: admin-only (Store has no login of its own).
  INSTAMART_PRODUCT_VIEW: 'INSTAMART_PRODUCT_VIEW',
  INSTAMART_PRODUCT_MANAGE: 'INSTAMART_PRODUCT_MANAGE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',

  FINANCE_VIEW: 'FINANCE_VIEW',
  SETTLEMENT_PROCESS: 'SETTLEMENT_PROCESS',
  SETTLEMENT_PAY: 'SETTLEMENT_PAY',
  COMMISSION_VIEW: 'COMMISSION_VIEW',
  COMMISSION_MANAGE: 'COMMISSION_MANAGE',

  PAYMENT_VIEW: 'PAYMENT_VIEW',
  REFUND_VIEW: 'REFUND_VIEW',
  REFUND_PROCESS: 'REFUND_PROCESS',
  WALLET_VIEW: 'WALLET_VIEW',
  WALLET_MANAGE: 'WALLET_MANAGE',

  LOCATION_VIEW: 'LOCATION_VIEW',
  LOCATION_CREATE: 'LOCATION_CREATE',
  LOCATION_UPDATE: 'LOCATION_UPDATE',
  LOCATION_DELETE: 'LOCATION_DELETE',

  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',

  ADMIN_USER_VIEW: 'ADMIN_USER_VIEW',
  ADMIN_USER_CREATE: 'ADMIN_USER_CREATE',
  ADMIN_USER_UPDATE: 'ADMIN_USER_UPDATE',
  ADMIN_USER_DELETE: 'ADMIN_USER_DELETE',

  COUPON_VIEW: 'COUPON_VIEW',
  COUPON_MANAGE: 'COUPON_MANAGE',
  OFFER_VIEW: 'OFFER_VIEW',
  OFFER_MANAGE: 'OFFER_MANAGE',
  BANNER_VIEW: 'BANNER_VIEW',
  BANNER_MANAGE: 'BANNER_MANAGE',
  // Browsing reviews is public (no permission needed — see reviews.routes);
  // this gates seeing HIDDEN ones and moderating (hide/unhide) them.
  REVIEW_VIEW: 'REVIEW_VIEW',
  REVIEW_MODERATE: 'REVIEW_MODERATE',

  ACTIVITY_LOG_VIEW: 'ACTIVITY_LOG_VIEW',

  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Default permission set granted to each admin role. SUPER_ADMIN implicitly bypasses all checks.
export const ROLE_DEFAULT_PERMISSIONS: Record<string, Permission[]> = {
  [ADMIN_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  // LOCATION_ADMIN has full operational control within their assigned location(s)
  // — everything except platform-level admin-user/role management and finance
  // settlement processing, which stay with SUPER_ADMIN/FINANCE_ADMIN.
  [ADMIN_ROLES.LOCATION_ADMIN]: [
    PERMISSIONS.LOCATION_VIEW,
    PERMISSIONS.VENDOR_VIEW,
    PERMISSIONS.VENDOR_CREATE,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_APPROVE,
    PERMISSIONS.STORE_VIEW,
    PERMISSIONS.STORE_CREATE,
    PERMISSIONS.STORE_UPDATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.DELIVERY_VIEW,
    PERMISSIONS.DELIVERY_ASSIGN,
    PERMISSIONS.DELIVERY_REASSIGN,
    PERMISSIONS.DELIVERY_ZONE_VIEW,
    PERMISSIONS.DELIVERY_ZONE_MANAGE,
    PERMISSIONS.DELIVERY_PARTNER_VIEW,
    PERMISSIONS.DELIVERY_PARTNER_MANAGE,
    PERMISSIONS.DELIVERY_ISSUE_VIEW,
    PERMISSIONS.DELIVERY_ISSUE_MANAGE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.FOOD_CATALOG_VIEW,
    PERMISSIONS.FOOD_CATALOG_MANAGE,
    PERMISSIONS.FOOD_PRODUCT_VIEW,
    PERMISSIONS.FOOD_PRODUCT_MANAGE,
    PERMISSIONS.INSTAMART_CATALOG_VIEW,
    PERMISSIONS.INSTAMART_CATALOG_MANAGE,
    PERMISSIONS.INSTAMART_PRODUCT_VIEW,
    PERMISSIONS.INSTAMART_PRODUCT_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
  [ADMIN_ROLES.FOOD_ADMIN]: [
    PERMISSIONS.VENDOR_VIEW,
    PERMISSIONS.VENDOR_CREATE,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_APPROVE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.FOOD_CATALOG_VIEW,
    PERMISSIONS.FOOD_CATALOG_MANAGE,
    PERMISSIONS.FOOD_PRODUCT_VIEW,
    PERMISSIONS.FOOD_PRODUCT_MANAGE,
  ],
  [ADMIN_ROLES.INSTAMART_ADMIN]: [
    PERMISSIONS.STORE_VIEW,
    PERMISSIONS.STORE_CREATE,
    PERMISSIONS.STORE_UPDATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.INSTAMART_CATALOG_VIEW,
    PERMISSIONS.INSTAMART_CATALOG_MANAGE,
    PERMISSIONS.INSTAMART_PRODUCT_VIEW,
    PERMISSIONS.INSTAMART_PRODUCT_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
  ],
  [ADMIN_ROLES.VENDOR_ADMIN]: [
    PERMISSIONS.VENDOR_VIEW,
    PERMISSIONS.VENDOR_CREATE,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_APPROVE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.FOOD_CATALOG_VIEW,
    PERMISSIONS.FOOD_CATALOG_MANAGE,
    PERMISSIONS.FOOD_PRODUCT_VIEW,
    PERMISSIONS.FOOD_PRODUCT_MANAGE,
  ],
  [ADMIN_ROLES.DELIVERY_ADMIN]: [
    PERMISSIONS.DELIVERY_VIEW,
    PERMISSIONS.DELIVERY_ASSIGN,
    PERMISSIONS.DELIVERY_REASSIGN,
    PERMISSIONS.DELIVERY_ZONE_VIEW,
    PERMISSIONS.DELIVERY_ZONE_MANAGE,
    PERMISSIONS.DELIVERY_PARTNER_VIEW,
    PERMISSIONS.DELIVERY_PARTNER_MANAGE,
    PERMISSIONS.DELIVERY_ISSUE_VIEW,
    PERMISSIONS.DELIVERY_ISSUE_MANAGE,
  ],
  [ADMIN_ROLES.FINANCE_ADMIN]: [
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.SETTLEMENT_PROCESS,
    PERMISSIONS.SETTLEMENT_PAY,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.REFUND_VIEW,
    PERMISSIONS.REFUND_PROCESS,
    PERMISSIONS.WALLET_VIEW,
    PERMISSIONS.WALLET_MANAGE,
    PERMISSIONS.COMMISSION_VIEW,
    PERMISSIONS.COMMISSION_MANAGE,
  ],
  [ADMIN_ROLES.MARKETING_ADMIN]: [
    PERMISSIONS.COUPON_VIEW,
    PERMISSIONS.COUPON_MANAGE,
    PERMISSIONS.OFFER_VIEW,
    PERMISSIONS.OFFER_MANAGE,
    PERMISSIONS.BANNER_VIEW,
    PERMISSIONS.BANNER_MANAGE,
  ],
  [ADMIN_ROLES.SUPPORT_ADMIN]: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.DELIVERY_VIEW,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.REFUND_VIEW,
    PERMISSIONS.WALLET_VIEW,
    PERMISSIONS.REVIEW_VIEW,
    PERMISSIONS.REVIEW_MODERATE,
    PERMISSIONS.DELIVERY_ISSUE_VIEW,
    PERMISSIONS.DELIVERY_ISSUE_MANAGE,
  ],
};
