export const USER_TYPES = {
  CUSTOMER: 'CUSTOMER',
  VENDOR: 'VENDOR',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  ADMIN: 'ADMIN',
} as const;

export type UserType = (typeof USER_TYPES)[keyof typeof USER_TYPES];

export const ADMIN_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  LOCATION_ADMIN: 'LOCATION_ADMIN',
  FOOD_ADMIN: 'FOOD_ADMIN',
  INSTAMART_ADMIN: 'INSTAMART_ADMIN',
  VENDOR_ADMIN: 'VENDOR_ADMIN',
  DELIVERY_ADMIN: 'DELIVERY_ADMIN',
  FINANCE_ADMIN: 'FINANCE_ADMIN',
  MARKETING_ADMIN: 'MARKETING_ADMIN',
  SUPPORT_ADMIN: 'SUPPORT_ADMIN',
} as const;

export type AdminRole = (typeof ADMIN_ROLES)[keyof typeof ADMIN_ROLES];

export const ADMIN_ROLE_LIST = Object.values(ADMIN_ROLES);
