import { Schema, model, Document, Types } from 'mongoose';
import { SALARY_RECORD_STATUS } from '../constants/enums';

// One monthly salary slip for a delivery partner.
// Generated by the admin for a given (year, month); unique per partner-month.
// Snapshots the salary config values active at generation time so historical
// records remain accurate even after the config is later updated.
export interface IDeliveryPartnerSalaryRecord extends Document {
  _id: Types.ObjectId;
  deliveryPartnerId: Types.ObjectId;
  // Denormalised from DeliveryPartner for efficient location-scoped queries.
  locationId: Types.ObjectId;
  year: number;
  month: number; // 1–12
  // Snapshotted from DeliveryPartnerSalaryConfig at generation time.
  baseSalary: number;
  hasOwnVehicle: boolean;
  perKmRate: number;
  // Computed from DELIVERED deliveries in the period.
  totalDistance: number; // km
  deliveryCount: number;
  // vehicleAllowance = totalDistance × perKmRate  (0 when !hasOwnVehicle)
  vehicleAllowance: number;
  // totalPayout = baseSalary + vehicleAllowance  (what the partner is paid)
  totalPayout: number;
  // The sum of delivery fees charged to customers across these deliveries.
  // Per platform policy the entire delivery charge is admin earnings; this
  // field is for reporting only — it does NOT reduce the partner's payout.
  customerDeliveryChargeTotal: number;
  adminEarningsFromDelivery: number; // = customerDeliveryChargeTotal
  // Payout state
  status: string;
  paidAt?: Date;
  transactionReference?: string;
  // Delivered orders that contributed to this record.
  orderIds: Types.ObjectId[];
  createdAt: Date;
  updatedAt: Date;
}

const deliveryPartnerSalaryRecordSchema = new Schema<IDeliveryPartnerSalaryRecord>(
  {
    deliveryPartnerId: { type: Schema.Types.ObjectId, ref: 'DeliveryPartner', required: true, index: true },
    locationId: { type: Schema.Types.ObjectId, ref: 'Location', required: true, index: true },
    year: { type: Number, required: true },
    month: { type: Number, required: true, min: 1, max: 12 },
    baseSalary: { type: Number, required: true, min: 0 },
    hasOwnVehicle: { type: Boolean, default: false },
    perKmRate: { type: Number, default: 0, min: 0 },
    totalDistance: { type: Number, default: 0, min: 0 },
    deliveryCount: { type: Number, default: 0, min: 0 },
    vehicleAllowance: { type: Number, default: 0, min: 0 },
    totalPayout: { type: Number, required: true, min: 0 },
    customerDeliveryChargeTotal: { type: Number, default: 0, min: 0 },
    adminEarningsFromDelivery: { type: Number, default: 0, min: 0 },
    status: { type: String, enum: Object.values(SALARY_RECORD_STATUS), default: SALARY_RECORD_STATUS.PENDING, index: true },
    paidAt: { type: Date },
    transactionReference: { type: String },
    orderIds: { type: [{ type: Schema.Types.ObjectId, ref: 'Order' }], default: [] },
  },
  { timestamps: true },
);

// One record per partner per month.
deliveryPartnerSalaryRecordSchema.index({ deliveryPartnerId: 1, year: 1, month: 1 }, { unique: true });
deliveryPartnerSalaryRecordSchema.index({ locationId: 1, year: 1, month: 1, status: 1 });

export const DeliveryPartnerSalaryRecord = model<IDeliveryPartnerSalaryRecord>(
  'DeliveryPartnerSalaryRecord',
  deliveryPartnerSalaryRecordSchema,
);
